// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2g3WBzN-zxzyEb9AQS2_og19Nq2dlRxE',
    appId: '1:745883040763:web:e8dc0bb376aa6122bfa95e',
    messagingSenderId: '745883040763',
    projectId: 'edutracker-new',
    authDomain: 'edutracker-new.firebaseapp.com',
    storageBucket: 'edutracker-new.firebasestorage.app',
    measurementId: 'G-43M2P6PVYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTQtqPdXki02C9WsIzOadTd4o1qESVrWE',
    appId: '1:745883040763:android:7187779ac384754cbfa95e',
    messagingSenderId: '745883040763',
    projectId: 'edutracker-new',
    storageBucket: 'edutracker-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdkJNQJfhcTmgDnvVjHkYSg9iAzuym4_k',
    appId: '1:745883040763:ios:ffdc47204198cca6bfa95e',
    messagingSenderId: '745883040763',
    projectId: 'edutracker-new',
    storageBucket: 'edutracker-new.firebasestorage.app',
    androidClientId: '745883040763-faa5rame1gvkjssio7gfu74n3dfiodar.apps.googleusercontent.com',
    iosClientId: '745883040763-cqfkm1c7cfv88js5s5q8bns26al6ho0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.edutracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdkJNQJfhcTmgDnvVjHkYSg9iAzuym4_k',
    appId: '1:745883040763:ios:ffdc47204198cca6bfa95e',
    messagingSenderId: '745883040763',
    projectId: 'edutracker-new',
    storageBucket: 'edutracker-new.firebasestorage.app',
    androidClientId: '745883040763-faa5rame1gvkjssio7gfu74n3dfiodar.apps.googleusercontent.com',
    iosClientId: '745883040763-cqfkm1c7cfv88js5s5q8bns26al6ho0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.edutracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2g3WBzN-zxzyEb9AQS2_og19Nq2dlRxE',
    appId: '1:745883040763:web:9386a9eeb9ae2447bfa95e',
    messagingSenderId: '745883040763',
    projectId: 'edutracker-new',
    authDomain: 'edutracker-new.firebaseapp.com',
    storageBucket: 'edutracker-new.firebasestorage.app',
    measurementId: 'G-YEDWL96258',
  );
}